// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ongxancyckedamghwfud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uZ3hhbmN5Y2tlZGFtZ2h3ZnVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMjIxNjAsImV4cCI6MjA3MDY5ODE2MH0.HAb47mWJgw2lNfX4aYYqjxnAWI7MxNMWP-Rym6-DHHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});